# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - govet # Vet examines Go source code
    - errcheck # Check for unchecked errors
    - staticcheck # Static analysis
    - unused # Check for unused code
    - ineffassign # Detect ineffectual assignments
    - gocritic # Opinionated Go linter
    - misspell # Spell check
    - gosec # Security checks
    - dupl # Duplicate code detection
    - godot # Check comments end with period
    - gocyclo # Cyclomatic complexity

linters-settings:
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude test files from some checks
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - gocyclo
    # Exclude generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
